name: My Node Action
on:
  push:    
  workflow_dispatch:
  
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 16
      - run: npm install .
      - run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git add pull-requests; git commit -am 'new artifacts'; git push 
