name: My Node Action
on:
  push:    
  workflow_dispatch:
  
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          version: 16
      - run: npm install .
      - run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      - run: file tmp/*      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'pull-requests'
          author_name: Kiki
          author_email: support@kit.edu
          default_author: github_actions
          message: 'Auto-Commit'
          pull: '--rebase --autostash'